### ISSUE TITLE
Correct viewport width of the landing page on iOS devices

### ISSUE THREAD

**Issue by JLeone123** [umass-cicsoft/umass-cicsoft.github.io#11]
The viewport width on iOS devices is not covering the entire screen when the device is rotated.  It could just be an iOS issue, but we should strive to make sure the website looks professional on all devices and browsers.

**Comment by AVS1508** [comment]
@JLeone123 discovered that the issue is just how websites generally look in horizontal mode on iOS at least, regardless of the browser. The landing page should cover the entire height and width of the viewport because in the .html file, we have:
```
style="width: 100vw; height: 100vh"
```
to the div with `id=main-section` and added `class="container-fluid"` to the first div under the body tag - the one for the navbar. @JLeone123 also added:
```
height: 100%;
width: 100%;
```
style attributes to the html and body tags, so we're good!
